FROM postgres:14-bullseye

# MAINTAINER postgre

#RUN chmod 755 -R /var/lib/postgresql/data
#COPY ./postgresql.conf /postgresql.conf
# RUN chmod 644 /var/lib/postgresql/data/postgresql.conf
#CMD cat /postgresql.conf  /var/lib/postgresql/data/postgresql.conf
