name: openreports-api
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: openreports-api
    env_file:
      - .env.compose
    networks:
      default: null
    platform: linux/arm64
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: volume
        source: migration-data
        target: /app/src/main/resources/db/migration
    working_dir: /app
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: openreports-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TZ: Asia/Tokyo
    networks:
      default: null
    platform: linux/arm64
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  default:
    name: openreports
volumes:
  db-data:
    name: openreports-api_db-data
  migration-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './src/main/resources/db/migration'
