name: openreports-api
services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    container_name: openreports-api
    env_file:
      - .env.compose
    environment:
      LOCAL_STORAGE_TYPE: s3
    networks:
      default: null
    platform: linux/arm64
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: volume
        source: app-src
        target: /app/src
      - type: volume
        source: template-data
        target: /app/templates
        volume: {}
    working_dir: /app
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: openreports-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TZ: Asia/Tokyo
    networks:
      default: null
    platform: linux/arm64
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume: {}
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: openreports-redis
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data
        target: /data
        volume: {}
  localstack:
    build:
      context: ./docker/localstack
      dockerfile: Dockerfile
    container_name: openreports-localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - type: volume
        source: localstack-data
        target: /var/lib/localstack
        volume: {}
      - type: volume
        source: localstack-script
        target: /etc/localstack/init/ready.d/
networks:
  default:
    name: openreports
volumes:
  db-data:
    name: openreports-api_db-data
  template-data:
    name: openreports-api-template-data
  app-src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './src'
  redis-data:
    name: openreports-api_redis-data
  localstack-data:
    name: openreports-api_localstack-data
  localstack-script:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './docker/localstack/init'
