name: openreports-api
services:
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    container_name: openreports-api
    env_file:
      - .env.compose
    networks:
      default: null
    platform: linux/arm64
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: volume
        source: app-src
        target: /app/src
      - type: volume
        source: template-data
        target: /app/templates
        volume: {}
    working_dir: /app
  db:
    image: postgres:17-bookworm
    container_name: openreports-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TZ: Asia/Tokyo
    networks:
      default: null
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.4-alpine
    container_name: openreports-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
networks:
  default:
    name: openreports
volumes:
  db-data:
    name: openreports-api_db-data
  template-data:
    name: openreports-api-template-data
  app-src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './src'
  redis-data:
    name: openreports-api_redis-data
