version: '3.8'
services:
  api:
    container_name: openreports-api
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env.compose
    working_dir: /app
    volumes:
      - ./src/main/resources/db/migration:/app/src/main/resources/db/migration
    platform: linux/arm64
  db:
    container_name: openreports-db
    build: ./docker/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/postgresql/data
    platform: linux/arm64
#   libreoffice:
#     build: ./docker/libreoffice
#     environment:
#       TZ: "Asia/Tokyo"

volumes:
  db-data:

networks:
  default:
    name: openreports
