version: '3.8'
services:
  openreports_api:
    container_name: openreports_api
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
  openreports_db:
    build: ./docker/postgres
    container_name: openreports_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: openreports
      POSTGRES_DB: openreports
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
#   libreoffice:
#     build: ./docker/libreoffice
#     environment:
#       TZ: "Asia/Tokyo"

volumes:
  db-data:
