version: '3'
services:
  api:
    container_name: api
    build: ./docker/api
  db:
    build: ./docker/postgres
    container_name: db
    volumes:
      - "./src/main/resources/db:/docker-entrypoint-initdb.d"
      - ./var/lib/postgresql:/var/lib/postgresql
#      - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    networks:
      openreports:
        aliases:
          - db
#   libreoffice:
#     build: ./docker/libreoffice
#     environment:
#       TZ: "Asia/Tokyo"
networks:
  openreports:

