version: '3'

tasks:
  up:
    cmds:
      - docker compose up
  up-d:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  build:
    cmds:
      - docker compose build
    env:
       COMPOSE_DOCKER_CLI_BUILD: 1
       DOCKER_BUILCDKIT: 1
  migrateUp:
    deps: [up-d]
    cmds:
      - docker compose exec api sbt flywayMigrate
  migrateClean:
    deps: [up-d]
    cmds:
      - docker compose exec api sbt flywayClean


