addSbtPlugin("com.earldouglas" %% "xsbt-web-plugin" % "4.2.4")
addSbtPlugin("com.eed3si9n" %% "sbt-assembly" % "1.2.0")
addSbtPlugin("org.scalameta" %% "sbt-scalafmt" % "2.4.6")
addSbtPlugin("org.scala-sbt" %% "sbt-contraband" % "0.5.3")
addSbtPlugin("org.scalameta" %% "sbt-scalafmt" % "2.4.6")
//addSbtPlugin("jp.ijufumi.plugins" % "sbt-flyway" % "0.1.0-SNAPSHOT")
