@startuml

entity members {
  * id
  * email
  * name
  * password
    google_id
  * created_at
  * updated_at
  * versions
}

entity workspaces {
  * id
  * name
  * slug
  * created_at
  * updated_at
  * versions
}

entity workspace_members {
  * workspace_id
  * member_id
  * role_id
}

entity roles {
  * id
  * role_type
}

entity functions {
  * id
  * resource
  * action
}

entity role_functions {
  * id
  * role_id
  * function_id
}

entity data_sources {
  * id
  * name
  * url
  * username
  * password
  * driver_type_id
  * workspace_id
}

entity driver_types {
  * id
  * name
  * jdbc_driver_class
}

entity reports {
  * id
  * workspace_id
  * name
  * report_template_id
  * data_source_id
}

entity report_templates {
  * id
  * workspace_id
  * storage_id
  * name
  * file_path
  * storage_type: [local, s3]
  * file_size
  * is_seed
}

entity report_parameters {
  * id
  * workspace_id
  * parameter_type: [embedded_function, fixed_value]
    embedded_function_type
    value
}

entity report_report_parameters {
  * id
  * report_id
  * report_parameter_id
}

entity report_groups {
  * id
  * workspace_id
  * name
}

entity report_group_reports {
  * id
  * report_group_id
  * report_id
}

entity storage_s3s {
  * id
  * workspace_id
  * aws_access_key_id
  * aws_secret_access_key
  * aws_region
  * s3_bucket_name
}

workspaces --r{ workspace_members
workspace_members }--u members
workspace_members }--r{ roles
roles --{ role_functions
role_functions --r{ functions
workspaces --l{ data_sources
workspaces --{ reports
workspaces --{ report_templates
workspaces --{ report_groups
reports }-- report_templates
report_groups }--{ report_group_reports
report_group_reports }--{ reports
reports }--{ report_report_parameters
report_report_parameters }--{ report_parameters
driver_types --{ data_sources
data_sources --{ reports
workspaces --r{ storage_s3s
storage_s3s --{ report_templates

@enduml
