name: Create PlantUML images

on:
  push:
    paths:
      - docs/db/diagram.puml
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          brew install plantuml
  create:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Create image
        run: |
          cat ./docs/db/diagram.puml | plantuml -tsvg -p > ./docs/db/diagram.svg
  commit:
    needs: create
    runs-on: macos-latest
    steps:
      - name: Commit image
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Takafumi Iju
          author_email: ijufumi@gmail.com
          message: 'Create image file by GitHub Action(create-plantuml-images.yml).'
          add: './docs/db/diagram.svg'
          push: true
